-- Connect to the 'postgres' database first
-- CREATE the role with LOGIN:
CREATE ROLE ro_user LOGIN PASSWORD '~';

--switch to user db
ALTER DATABASE "ReportOrchestrator" OWNER TO ro_user;
ALTER SCHEMA adsmaster OWNER TO ro_user;
ALTER SCHEMA vantagemaster OWNER TO ro_user;
ALTER SCHEMA vantageanalyticdata OWNER TO ro_user;
ALTER SCHEMA dataanalytics OWNER TO ro_user;
ALTER SCHEMA public OWNER TO ro_user;

